[package]
authors = ["ustulation <ustulation@gmail.com>"]
description = "Prune dependency cache"
license = "GPL-3.0"
name = "cargo-prune"
readme = "README.md"
repository = "https://github.com/ustulation/cargo-prune"
version = "0.1.0"

[dependencies]
unwrap = "~1.1.0"
